from karel.stanfordkarel import *

# File: piles.py
# -----------------------------
# The warmup program defines a "main"
# function which should make Karel
# pick up all the beepers in the world.
def main():
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()

    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()
    
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()
    
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()

    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    move()
    pick_beeper()
    move()
    turn_right()
    
    move()
    move()
    move()
    move()
    move()
    move()
    
    # your code here
def turn_right():
    turn_left()
    turn_left()
  
    

    
    
# don't edit these next two lines
# they tell python to run your main function
if __name__ == '__main__':
    main()